import "@repo/ui/globals.css";

import { type Metadata } from "next";
import InventorySidebar from "../../../_components/inventory/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Total Mini & BMW",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function InventoryLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex h-screen flex-col">
      <main className="flex flex-row w-screen h-screen">
        <InventorySidebar />
        <div className="flex flex-col w-full">{children}</div>
      </main>
    </div>
  );
}
